name: server_abnormality_alert
description: "Server abnormality alert smartphone app Develop."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+15

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  async: ^2.11.0

  flutter_fadein: ^2.0.0

  shared_preferences: any

  sqflite: ^2.3.3
  path: ^1.9.0

  exif: ^3.3.0

  image: ^4.3.0

  flutter_image_compress: ^2.3.0


  webview_flutter: ^4.9.0


  table_calendar: any

  http: ^1.2.2

  intl: any

  cupertino_icons: ^1.0.8

  flutter_inappwebview: ^6.1.5

  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  pointer_interceptor: ^0.10.1+2
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2

  flutter_timezone: any
  flutter_launcher_icons: any
  launcher_name: ^1.0.2

  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^18.0.1
  flutter_ringtone_player: ^4.0.0+3
  audio_service: ^0.18.15

  vibration: ^2.0.1
  audioplayers: ^6.1.0

dependency_overrides:

dev_dependencies:
  flutter_launcher_icons: ^0.14.0

launcher_name:
  default: "Server Monitoring"


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 24
  image_path: assets/appicon/google_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/appicon/google_icon.png

flutter_test:
  sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/audio/Warning-Siren01-1.mp3
